name: "CI"
on:
  push:
    branches: ['**']
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - name: Set up Ant
        uses: cedx/setup-ant@v3
        with:
          optional-tasks: true
          version: latest
      - run: ant
      - uses: actions/upload-artifact@v4
        with:
          name: passwdhash-lib.jdk-${{ matrix.jdk }}
          path: library/dist
      - uses: actions/upload-artifact@v4
        with:
          name: passwdhash-cli.jdk-${{ matrix.jdk }}
          path: frontend/dist
