name: "CI"
on:
  push:
    branches: ['**']
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - uses: cedx/setup-ant@v3
        with:
          optional-tasks: true
          version: latest
      - run: ant release
      - run: |
          mv -v core-lib/dist/passwdhash-lib-jdk${{ matrix.jdk }}.jar passwdhash-${{ github.ref_name }}-lib-jdk${{ matrix.jdk }}.jar
          mv -v frontend/dist/passwdhash-cli-jdk${{ matrix.jdk }}.jar passwdhash-${{ github.ref_name }}-cli-jdk${{ matrix.jdk }}.jar
      - uses: actions/upload-artifact@v4
        with:
          name: dist.passwdhash.jdk-${{ matrix.jdk }}
          path: passwdhash-*.jar

  release:
    if: ${{ github.event_name == 'release' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist.passwdhash.*
          path: artifacts
          merge-multiple: true
      - uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: artifacts/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
